### ISSUE TITLE
Would be great if it downloaded current year data

### ISSUE THREAD

**Issue by johnrharley** [NOAA-EDAB/buoydata#3]
Thanks for creating this, I was finding it tedious to combine datasets accessed through `rnoaa::buoy()`.

It might be a specific bug, I haven't peered through the source code, but when I run `buoydata::get_buoy_data(buoyid="jnea2", year=2000:2020, outDir = here::here("output"))`  
it says there is no data for 2020. There are 4 months of QA/QC'd data for that buoy the data are just organized by month instead of grouped per year so the request structure for the zipped file looks slightly different.

Not a huge problem for most I imagine but would be a nice enhancement.

**Comment by andybeet** [comment]
@johnrharley this is long overdue, and im sure you have sorted this out. But it looks like the current year will not be present in this data pull. I am planning on reaching out and seeing if they have an API i can interact with rather that web scraping. This might help in providing up to date data
